/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        bg:        'var(--bg)',
        'bg-alt':  'var(--bg-alt)',
        surface:   'var(--surface)',
        surface2:  'var(--surface2)',
        surface3:  'var(--surface3)',
        border:    'var(--border)',
        border2:   'var(--border2)',
        brand:     'var(--brand)',
        'brand-dim': 'var(--brand-dim)',
        'brand-glow':'var(--brand-glow)',
        'brand-bg':  'var(--brand-bg)',
        accent:    'var(--accent)',
        'accent-bg':'var(--accent-bg)',
        success:   'var(--success)',
        warning:   'var(--warning)',
        error:     'var(--error)',
        info:      'var(--info)',
        ink:       'var(--text)',
        'ink-mid': 'var(--text-mid)',
        muted:     'var(--text-muted)',
        faint:     'var(--text-faint)',
        paper:     'var(--paper)',
      },
      fontFamily: {
        mono:  ['"JetBrains Mono"', '"Courier Prime"', 'monospace'],
        serif: ['"Fraunces"', '"Noto Serif SC"', 'Georgia', 'serif'],
        sans:  ['"Inter"', 'system-ui', '-apple-system', 'sans-serif'],
      },
      borderRadius: {
        sm:  'var(--radius-sm)',
        md:  'var(--radius-md)',
        lg:  'var(--radius-lg)',
        xl:  'var(--radius-xl)',
      },
      boxShadow: {
        sm:    'var(--shadow-sm)',
        md:    'var(--shadow-md)',
        lg:    'var(--shadow-lg)',
        modal: 'var(--shadow-modal)',
        card:  '0 1px 4px rgba(0,0,0,0.08), 0 0 0 1px rgba(0,0,0,0.04)',
        lift:  '0 4px 16px rgba(0,0,0,0.10), 0 0 0 1px rgba(0,0,0,0.04)',
      },
      animation: {
        'fade-in':    'fadeIn 0.2s ease forwards',
        'slide-up':   'slideUp 0.25s ease forwards',
        'bounce-in':  'bounceIn 0.25s cubic-bezier(0.34,1.56,0.64,1) forwards',
        'slide-in-right': 'slideInRight 0.2s ease forwards',
      },
      keyframes: {
        fadeIn:  { from: { opacity: '0', transform: 'translateY(4px)' }, to: { opacity: '1', transform: 'translateY(0)' } },
        slideUp: { from: { opacity: '0', transform: 'translateY(12px)' }, to: { opacity: '1', transform: 'translateY(0)' } },
        bounceIn:{ from: { opacity: '0', transform: 'scale(0.92)' }, to: { opacity: '1', transform: 'scale(1)' } },
        slideInRight: { from: { opacity: '0', transform: 'translateX(16px)' }, to: { opacity: '1', transform: 'translateX(0)' } },
      },
    },
  },
  plugins: [],
}
